import type { EdgeSemantic } from '../document/types';
import { DELIVERY_SEMANTICS, defineChain, defineFanOut, hasInboundEvidence, hasOutboundSemantic, isExplicit } from './families';
import type { ContinuationRule, Neighborhood } from './types';

/**
 * The shipped rules. Each is something a developer would have drawn next anyway, already has
 * strong matrix semantics behind it, and depends on graph shape rather than a guess about business
 * intent. Nothing from a plain Service, an Actor, a Data Store, a Cache, a File System, a Search
 * Index or a bare Component ever appears unprompted: too many valid next moves, so no one of them
 * is *the* move. Services and Actors do get a short list of `surfaces: 'invoke'` alternatives — only
 * reachable by asking with `]`, ordered by what points at the anchor (`role.ts`) — see
 * `docs/reference/semantics.md`'s "Nothing starts unprompted..." note and this file's own family
 * comments for exactly which pairings were considered and rejected. A Table gets one asked-for
 * rule, and only once the graph shows it is a pipeline stage (`table-next-stage`). Where asking
 * still finds nothing, `ambiguity.ts` says why — that is where "no guess" is written down.
 *
 * Some rules are hand-written standalone objects (the original five, plus the two dead-letter
 * variants); others are generated by `families.ts`'s `defineFanOut` for a source category with
 * several valid targets. Both shapes end up as plain `ContinuationRule`s — nothing downstream of
 * `RULES` needs to know which. Growing this list is not an invitation to add a rule for every
 * legal `MATRIX` pairing: legality and "worth suggesting" are different questions, and every
 * family below is still called with a hand-chosen evidence check and hand-authored reasons, not a
 * generator that walks the matrix on its own.
 *
 * **Order is the baseline ranking.** With no contextual signal firing (`rank.ts`), an earlier rule
 * outranks a later one of the same confidence and tier. The engine (`engine.ts`) applies the
 * matrix, the generic suppressions and confidence — a rule only says *when it applies* and *what it
 * adds*, never whether the connection is legal.
 */

/**
 * Where the machinery of a running system is *not* worth suggesting.
 *
 * A System Context view is people, this system and the systems around it — a dead-letter queue or
 * a cache in that picture is exactly the detail the view exists to leave out. So every rule about
 * infrastructure goes quiet when the view has been called a system overview, and is unchanged
 * everywhere else, which is every canvas that has never said what it is.
 */
const NOT_IN_AN_OVERVIEW = ['context'] as const;

const TOPIC_FAN_OUT_QUEUE: ContinuationRule = {
  id: 'topic-fan-out-queue',
  tier: 'primary',
  label: 'Queue',
  reason: 'This topic has a publisher but no delivery path.',
  silentAt: NOT_IN_AN_OVERVIEW,
  when: (nb, trigger) =>
    nb.category === 'topic' && (isExplicit(trigger) || (hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS))),
  fragment: () => ({
    nodes: [{ key: 'queue', type: 'queue', queueKind: 'queue' }],
    edges: [{ from: 'anchor', to: 'queue' }],
  }),
  // A topic fans out: continuing from one that already feeds a queue means *another* queue.
  repeatable: isExplicit,
  branches: true,
};

/**
 * A whole subscriber at once — the shape a Topic's delivery path almost always takes. Never
 * unprompted (the single Queue is the quiet suggestion, and chaining reaches the Worker anyway);
 * offered when asked, and ranked first once the Topic already has a subscriber of exactly this
 * shape (`rank.ts`'s sibling-branch signal).
 */
const TOPIC_SUBSCRIBER = defineChain({
  id: 'topic-subscriber',
  tier: 'secondary',
  label: 'Queue → Worker',
  reason: 'A subscriber: its own queue and the worker consuming it.',
  sources: ['topic'],
  evidence: (nb) => TOPIC_FAN_OUT_QUEUE.when(nb, 'select'),
  chain: [
    { type: 'queue', queueKind: 'queue' },
    { type: 'service', serviceKind: 'worker' },
  ],
  branches: true,
  silentAt: NOT_IN_AN_OVERVIEW,
});

const TOPIC_FAN_OUT_WORKER: ContinuationRule = {
  id: 'topic-fan-out-worker',
  tier: 'secondary',
  label: 'Worker',
  reason: 'Subscribers can also receive directly from the topic.',
  when: TOPIC_FAN_OUT_QUEUE.when,
  fragment: () => ({
    nodes: [{ key: 'worker', type: 'service', serviceKind: 'worker' }],
    edges: [{ from: 'anchor', to: 'worker' }],
  }),
  repeatable: isExplicit,
  branches: true,
};

const QUEUE_CONSUMER: ContinuationRule = {
  id: 'queue-consumer',
  tier: 'primary',
  label: 'Worker',
  reason: 'This queue has no consumer.',
  silentAt: NOT_IN_AN_OVERVIEW,
  // `categoryOf` folds a Stream into `queue` (consuming from one is the same move) and lifts a
  // dead-letter queue out of it — a DLQ with no re-drive worker is normal, not unfinished.
  when: (nb, trigger) =>
    nb.category === 'queue' && (isExplicit(trigger) || (hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS))),
  fragment: () => ({
    nodes: [{ key: 'worker', type: 'service', serviceKind: 'worker' }],
    edges: [{ from: 'anchor', to: 'worker' }],
  }),
  // Competing consumers are what a queue is for.
  repeatable: isExplicit,
};

const QUEUE_DEAD_LETTER: ContinuationRule = {
  id: 'queue-dead-letter',
  tier: 'secondary',
  label: 'Dead-letter queue',
  reason: 'This queue has a consumer but no dead-letter path.',
  silentAt: NOT_IN_AN_OVERVIEW,
  // The literal `queueKind === 'queue'`, not `categoryOf`, for the same reason `addDeadLetterQueue`
  // uses it: a Stream's dead-letter destination is a separate topic (see `stream-dead-letter`
  // below), not a queue-shaped DLQ.
  when: (nb) =>
    nb.node.type === 'queue' &&
    nb.node.queueKind === 'queue' &&
    nb.node.deliveryRole === undefined &&
    hasOutboundSemantic(nb, 'consumes') &&
    !hasOutboundSemantic(nb, 'deadLetters'),
  fragment: () => ({
    nodes: [{ key: 'dlq', type: 'queue', queueKind: 'queue', deliveryRole: 'dead-letter' }],
    // Three attempts is the conventional default — the one opinion `addDeadLetterQueue` has too.
    edges: [{ from: 'anchor', to: 'dlq', deliveryAttempts: 3 }],
  }),
};

const STREAM_DEAD_LETTER: ContinuationRule = {
  id: 'stream-dead-letter',
  tier: 'secondary',
  label: 'Dead-letter topic',
  reason: 'This stream has a consumer but no dead-letter path.',
  silentAt: NOT_IN_AN_OVERVIEW,
  // The literal `queueKind === 'stream'`, not `categoryOf` (which folds it into `queue`) — a
  // Stream's dead-letter destination reads as a Topic, unlike a plain Queue's. The fragment below
  // still resolves to the existing, already-valid `queue>deadLetter` matrix row regardless: giving
  // the new node `deliveryRole: 'dead-letter'` puts it in `NodeCategory: 'deadLetter'` no matter
  // what its `queueKind` is (see `categoryOf`'s precedence) — no new matrix row needed, `queueKind`
  // only changes how it's drawn.
  when: (nb) =>
    nb.node.type === 'queue' &&
    nb.node.queueKind === 'stream' &&
    hasOutboundSemantic(nb, 'consumes') &&
    !hasOutboundSemantic(nb, 'deadLetters'),
  fragment: () => ({
    nodes: [{ key: 'dlq', type: 'queue', queueKind: 'topic', deliveryRole: 'dead-letter' }],
    edges: [{ from: 'anchor', to: 'dlq', deliveryAttempts: 3 }],
  }),
};

const GATEWAY_ROUTE: ContinuationRule = {
  id: 'gateway-route',
  tier: 'primary',
  label: 'Service',
  reason: "This gateway doesn't route to anything yet.",
  silentAt: NOT_IN_AN_OVERVIEW,
  when: (nb, trigger) => nb.category === 'gateway' && (isExplicit(trigger) || (nb.in.length > 0 && nb.out.length === 0)),
  fragment: () => ({
    nodes: [{ key: 'service', type: 'service', serviceKind: 'api' }],
    edges: [{ from: 'anchor', to: 'service' }],
  }),
  repeatable: isExplicit,
  // A gateway's routes fan out to many services.
  branches: true,
};

/**
 * A Scheduler with nothing to trigger yet — `MATRIX['scheduler>service']` and
 * `['scheduler>worker']` both default to `'triggers'`. Unlike the fan-out families above, no
 * inbound evidence is required: a Scheduler fires on its own interval, not because something fed
 * it, so "has it triggered anything downstream" is the whole question.
 */
const SCHEDULER_TRIGGER = defineFanOut(
  ['scheduler'],
  (nb) => nb.out.length === 0,
  [
    {
      id: 'scheduler-trigger-service',
      tier: 'primary',
      label: 'Service',
      reason: "This scheduler doesn't trigger anything yet.",
      node: { type: 'service' },
    },
    {
      id: 'scheduler-trigger-worker',
      tier: 'secondary',
      label: 'Worker',
      reason: 'A scheduled job is usually a Worker.',
      node: { type: 'service', serviceKind: 'worker' },
    },
  ],
  { silentAt: NOT_IN_AN_OVERVIEW },
);

/**
 * An Object Storage bucket already being written to with nowhere for that write to notify —
 * `MATRIX['objectStorage>queue']`/`['objectStorage>topic']` (both `publishes`/`event`), the one
 * storage kind that legitimately triggers a downstream event. Same "already receiving, nothing
 * leaves yet" evidence the Topic fan-out above uses, reused via `defineFanOut` rather than
 * repeated by hand. There is no Worker target here — Object Storage has no `worker` row in the
 * matrix, so `fragmentIsValid` would reject one anyway; it is simply never offered as a target.
 */
const OBJECT_STORAGE_FAN_OUT = defineFanOut(
  ['objectStorage'],
  (nb) => hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS),
  [
    {
      id: 'object-storage-fan-out-queue',
      tier: 'primary',
      label: 'Queue',
      reason: 'Uploads here have nowhere to notify yet.',
      node: { type: 'queue', queueKind: 'queue' },
    },
    {
      id: 'object-storage-fan-out-topic',
      tier: 'secondary',
      label: 'Topic',
      reason: 'Multiple subscribers can watch this bucket through a topic instead.',
      node: { type: 'queue', queueKind: 'topic' },
    },
  ],
  { branches: true, silentAt: NOT_IN_AN_OVERVIEW },
);

/**
 * A Port already depended on but not implemented by anything — `MATRIX['port>component']`/
 * `['port>service']` (both `implementedBy`). Same "has inbound, nothing routed yet" evidence
 * `gateway-route` above already uses.
 */
const PORT_IMPLEMENTATION = defineFanOut(
  ['port'],
  (nb) => hasInboundEvidence(nb) && nb.out.length === 0,
  [
    {
      id: 'port-implementation-component',
      tier: 'primary',
      label: 'Component',
      reason: "This port isn't implemented by anything yet.",
      node: { type: 'component' },
    },
    {
      id: 'port-implementation-service',
      tier: 'secondary',
      label: 'Service',
      reason: 'A port can also be implemented by a whole service.',
      node: { type: 'service' },
    },
  ],
  { silentAt: NOT_IN_AN_OVERVIEW },
);

/**
 * An Adapter's next move is the Port it sits behind — on the driving side it calls one, on the
 * driven side it implements one, and the diagram can't tell which, so the connector is inferred
 * as the neutral `uses` (`MATRIX['component>port']`) and the adapter's direction is left to the
 * user. Asked-for only: an Adapter alone isn't evidence it's missing anything, and unlike the
 * Component family this needs no level — the adapter kind itself says ports-and-adapters.
 */
const ADAPTER_PORT: ContinuationRule = {
  id: 'adapter-port',
  tier: 'secondary',
  label: 'Port',
  reason: 'The contract this adapter sits behind.',
  when: (nb, trigger) => nb.category === 'component' && nb.node.componentKind === 'adapter' && isExplicit(trigger),
  fragment: () => ({
    nodes: [{ key: 'target', type: 'component', componentKind: 'port' }],
    edges: [{ from: 'anchor', to: 'target' }],
  }),
  silentAt: NOT_IN_AN_OVERVIEW,
};

/**
 * The next stage of a pipeline of tables — Bronze → Silver → Gold, raw → cleaned → curated.
 *
 * A Table on its own is the most overloaded shape there is: the Transactional Outbox's outbox, a
 * read model's projection, a CDC source and a plain business table are all the same
 * `databaseKind: 'table'`, and nothing but their labels tells them apart — so a Table alone gets
 * no guess (`ambiguity.ts`). What does tell: a Table that another store already *feeds*
 * (`MATRIX['database>database']`, `ingests`/`transforms`) is a stage in a pipeline, and a pipeline's
 * next move is another stage. Asked-for only, and never a second branch — one table flows into the
 * next, and the engine's own suppression stops once it already does.
 */
const PIPELINE_FEEDS: readonly EdgeSemantic[] = ['ingests', 'transforms'];

const TABLE_NEXT_STAGE: ContinuationRule = {
  id: 'table-next-stage',
  tier: 'secondary',
  label: 'Table',
  reason: 'The next stage of the pipeline this table is part of.',
  when: (nb, trigger) =>
    isExplicit(trigger) &&
    nb.node.type === 'database' &&
    nb.node.databaseKind === 'table' &&
    nb.in.some(({ edge, category }) => category === 'database' && edge.semantic !== undefined && PIPELINE_FEEDS.includes(edge.semantic)),
  fragment: () => ({
    nodes: [{ key: 'target', type: 'database', databaseKind: 'table' }],
    edges: [{ from: 'anchor', to: 'target' }],
  }),
  silentAt: NOT_IN_AN_OVERVIEW,
};

/**
 * A Worker already fed by something but with no outbound connection at all yet — narrower than
 * the other families' evidence (zero outbound of *any* kind, not just a missing delivery path),
 * since "should this worker index something" is otherwise exactly the kind of guess `docs/reference/
 * semantics.md` warns a plain Service against. `MATRIX['worker>searchIndex']` defaults to
 * `'indexes'` (overriding the generic `service>searchIndex` default of `'searches'`), so a Worker
 * is the one service-family kind with a real, opinionated row here — a plain Service still gets no
 * rule at all.
 */
const WORKER_INDEXES = defineFanOut(
  ['worker'],
  (nb) => hasInboundEvidence(nb) && nb.out.length === 0,
  [
    {
      id: 'worker-indexes',
      tier: 'secondary',
      label: 'Search Index',
      reason: "This worker doesn't index anything yet.",
      node: { type: 'database', databaseKind: 'search-index' },
    },
  ],
  { silentAt: NOT_IN_AN_OVERVIEW },
);

/**
 * Where a Service (or Worker) could go next — offered only when asked (`surfaces: 'invoke'`), never
 * unprompted and never in the Quick Connect menu, whose presets already cover these shapes. There
 * is no evidence check because there is no quiet case: this is the list `]` cycles through. What
 * leads it depends on what points at the anchor — a Service behind a gateway leads with its own
 * data, one draining a queue with where the result lands (`role.ts`) — and `rank.ts` pushes down
 * what the anchor already does (a Service already writing to a Data Store gets another Data Store
 * last, a Cache not). Every row is a plain matrix default:
 * `service>database`/`>cache` writes, `>topic`/`>queue` publishes, `>service`/`>external` calls —
 * a Worker reaches the same rows through the matrix's service fallback.
 *
 * Four of them go quiet in a view that has said it is a system overview. What a system stores and
 * what it publishes are true, but they are a level down from the conversation: answering "what
 * next?" there with a Data Store is how a picture of a business stops being one. The two that stay
 * — another system, and a system someone else runs — are the answer at that altitude.
 */
const SERVICE_NEXT = defineFanOut(
  ['service', 'worker'],
  () => false,
  [
    {
      id: 'service-data-store',
      tier: 'secondary',
      label: 'Data Store',
      reason: 'Services usually own their data.',
      node: { type: 'database' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
    {
      id: 'service-topic',
      tier: 'secondary',
      label: 'Topic',
      reason: 'Publish events other parts of the system react to.',
      node: { type: 'queue', queueKind: 'topic' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
    {
      id: 'service-queue',
      tier: 'secondary',
      label: 'Queue',
      reason: 'Hand work off to be processed later.',
      node: { type: 'queue', queueKind: 'queue' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
    { id: 'service-service', tier: 'secondary', label: 'Service', reason: 'Call another service.', node: { type: 'service' } },
    {
      id: 'service-cache',
      tier: 'secondary',
      label: 'Cache',
      reason: 'Keep hot reads close.',
      node: { type: 'database', databaseKind: 'cache' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
    {
      id: 'service-external',
      tier: 'secondary',
      label: 'External System',
      reason: 'Call a system outside this one.',
      node: { type: 'service', serviceKind: 'external' },
    },
  ],
  { surfaces: 'invoke' },
);

/** The anchor already writes somewhere a search index would be built from. A Cache or a File
 *  System is not that: one is a copy of reads, the other is where bytes sit. */
function writesToAStore(nb: Neighborhood): boolean {
  return nb.out.some(
    ({ edge, category }) => edge.semantic === 'writes' && (category === 'database' || category === 'objectStorage'),
  );
}

/**
 * The one Service row that has to be earned. `matrix service>searchIndex` is `searches` — the
 * queries a data store can't answer — so it only means anything once there is a data store: an
 * index in front of nothing is a shape with no content. Listed separately rather than inside
 * `SERVICE_NEXT` because that family is unconditional by design, and this is the opposite.
 *
 * Not `repeatable`: one search index is the answer, and the engine's own suppression stops a
 * second. A Worker is deliberately not a source here — `WORKER_INDEXES` is already a Worker's
 * search index, and offering both would put the same shape in the list twice under two reasons.
 */
const SERVICE_SEARCH_INDEX: ContinuationRule = {
  id: 'service-search-index',
  tier: 'secondary',
  label: 'Search Index',
  reason: "Queries its data store can't answer.",
  when: (nb, trigger) => nb.category === 'service' && isExplicit(trigger) && writesToAStore(nb),
  fragment: () => ({
    nodes: [{ key: 'target', type: 'database', databaseKind: 'search-index' }],
    edges: [{ from: 'anchor', to: 'target' }],
  }),
  surfaces: 'invoke',
  silentAt: NOT_IN_AN_OVERVIEW,
};

/**
 * Where a request from an Actor enters — only when asked, like `SERVICE_NEXT`. `actor>service`
 * calls is the matrix row; a Gateway and an API reach it through the service fallback.
 */
const ACTOR_NEXT = defineFanOut(
  ['actor'],
  () => false,
  [
    {
      id: 'actor-gateway',
      tier: 'secondary',
      label: 'Gateway',
      reason: 'Requests usually enter through a gateway.',
      node: { type: 'service', serviceKind: 'gateway' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
    {
      id: 'actor-api',
      tier: 'secondary',
      label: 'API',
      reason: 'Or call an API directly.',
      node: { type: 'service', serviceKind: 'api' },
      silentAt: NOT_IN_AN_OVERVIEW,
    },
  ],
  { surfaces: 'invoke' },
);

/**
 * What a system overview is made of: people, the system, and the systems around it.
 *
 * Only offered where the view has actually been called a System Context — which is what makes
 * "System" the right word for a plain Service here, and what keeps these suggestions out of every
 * ordinary canvas. Both are `surfaces: 'invoke'`: at this altitude the next move is a judgement
 * about scope, not a shape the graph implies, so Draft Canvas answers when asked and not before.
 */
const CONTEXT_NEXT = defineFanOut(
  ['actor'],
  () => false,
  [
    {
      id: 'person-system',
      tier: 'secondary',
      label: 'System',
      reason: 'The system this person uses.',
      node: { type: 'service', text: 'System' },
    },
    {
      id: 'person-external',
      tier: 'secondary',
      label: 'External System',
      reason: 'Or a system someone else runs.',
      node: { type: 'service', serviceKind: 'external' },
    },
  ],
  { surfaces: 'invoke', levels: ['context'] },
);

/**
 * Inside one running thing: its parts, and what they keep their data in.
 *
 * A Component's next move is never obvious from the graph — a controller, a use case and a
 * repository all look identical to a diagram — so like the Service family these answer only when
 * asked. The names are placeholders in the ordinary sense (`textOrigin: 'auto'`): typing over one
 * is the expected first thing to do with it.
 */
const COMPONENT_NEXT = defineFanOut(
  ['component'],
  () => false,
  [
    {
      id: 'component-component',
      tier: 'secondary',
      label: 'Component',
      reason: 'The next part of this one — a use case, a domain model, a repository.',
      node: { type: 'component' },
    },
    {
      id: 'component-adapter',
      tier: 'secondary',
      label: 'Adapter',
      reason: 'Where this reaches something outside itself.',
      node: { type: 'component', componentKind: 'adapter' },
    },
    {
      id: 'component-data-store',
      tier: 'secondary',
      label: 'Data Store',
      reason: 'What it reads and writes.',
      node: { type: 'database' },
    },
  ],
  { surfaces: 'invoke', levels: ['component'] },
);

export const RULES: readonly ContinuationRule[] = [
  TOPIC_FAN_OUT_QUEUE,
  TOPIC_SUBSCRIBER,
  TOPIC_FAN_OUT_WORKER,
  QUEUE_CONSUMER,
  QUEUE_DEAD_LETTER,
  STREAM_DEAD_LETTER,
  GATEWAY_ROUTE,
  ...SCHEDULER_TRIGGER,
  ...OBJECT_STORAGE_FAN_OUT,
  ...PORT_IMPLEMENTATION,
  ADAPTER_PORT,
  TABLE_NEXT_STAGE,
  ...SERVICE_NEXT,
  SERVICE_SEARCH_INDEX,
  ...WORKER_INDEXES,
  ...ACTOR_NEXT,
  ...CONTEXT_NEXT,
  ...COMPONENT_NEXT,
];

