import { DELIVERY_SEMANTICS, defineFanOut, hasInboundEvidence, hasOutboundSemantic } from './families';
import type { ContinuationRule } from './types';

/**
 * The shipped rules. Each is something a developer would have drawn next anyway, already has
 * strong matrix semantics behind it, and depends on graph shape rather than a guess about business
 * intent. Anything from a plain Service, an Actor, a Data Store, a Cache, a File System, a Search
 * Index or a bare Component is deliberately absent: too many valid next moves, so no one of them
 * is *the* move — see `docs/SEMANTICS.md`'s "Deliberately no rule..." note and this file's own
 * family comments for exactly which pairings were considered and rejected.
 *
 * Some rules are hand-written standalone objects (the original five, plus the two dead-letter
 * variants); others are generated by `families.ts`'s `defineFanOut` for a source category with
 * several valid targets. Both shapes end up as plain `ContinuationRule`s — nothing downstream of
 * `RULES` needs to know which. Growing this list is not an invitation to add a rule for every
 * legal `MATRIX` pairing: legality and "worth suggesting" are different questions, and every
 * family below is still called with a hand-chosen evidence check and hand-authored reasons, not a
 * generator that walks the matrix on its own.
 *
 * **Order is ranking.** Within a tier, an earlier rule outranks a later one; there are no scores.
 * The engine (`engine.ts`) applies the matrix, the generic suppressions and the tier gate — a rule
 * only says *when it applies* and *what it adds*, never whether the connection is legal.
 */

const TOPIC_FAN_OUT_QUEUE: ContinuationRule = {
  id: 'topic-fan-out-queue',
  tier: 'primary',
  label: 'Queue',
  reason: 'This topic has a publisher but no delivery path.',
  when: (nb, trigger) =>
    nb.category === 'topic' && (trigger === 'drop' || (hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS))),
  fragment: () => ({
    nodes: [{ key: 'queue', type: 'queue', queueKind: 'queue' }],
    edges: [{ from: 'anchor', to: 'queue' }],
  }),
  // A topic fans out: continuing from one that already feeds a queue means *another* queue.
  repeatable: (trigger) => trigger === 'drop',
};

const TOPIC_FAN_OUT_WORKER: ContinuationRule = {
  id: 'topic-fan-out-worker',
  tier: 'secondary',
  label: 'Worker',
  reason: 'Subscribers can also receive directly from the topic.',
  when: TOPIC_FAN_OUT_QUEUE.when,
  fragment: () => ({
    nodes: [{ key: 'worker', type: 'service', serviceKind: 'worker' }],
    edges: [{ from: 'anchor', to: 'worker' }],
  }),
  repeatable: (trigger) => trigger === 'drop',
};

const QUEUE_CONSUMER: ContinuationRule = {
  id: 'queue-consumer',
  tier: 'primary',
  label: 'Worker',
  reason: 'This queue has no consumer.',
  // `categoryOf` folds a Stream into `queue` (consuming from one is the same move) and lifts a
  // dead-letter queue out of it — a DLQ with no re-drive worker is normal, not unfinished.
  when: (nb, trigger) =>
    nb.category === 'queue' && (trigger === 'drop' || (hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS))),
  fragment: () => ({
    nodes: [{ key: 'worker', type: 'service', serviceKind: 'worker' }],
    edges: [{ from: 'anchor', to: 'worker' }],
  }),
  // Competing consumers are what a queue is for.
  repeatable: (trigger) => trigger === 'drop',
};

const QUEUE_DEAD_LETTER: ContinuationRule = {
  id: 'queue-dead-letter',
  tier: 'secondary',
  label: 'Dead-letter queue',
  reason: 'This queue has a consumer but no dead-letter path.',
  // The literal `queueKind === 'queue'`, not `categoryOf`, for the same reason `addDeadLetterQueue`
  // uses it: a Stream's dead-letter destination is a separate topic (see `stream-dead-letter`
  // below), not a queue-shaped DLQ.
  when: (nb) =>
    nb.node.type === 'queue' &&
    nb.node.queueKind === 'queue' &&
    nb.node.deliveryRole === undefined &&
    hasOutboundSemantic(nb, 'consumes') &&
    !hasOutboundSemantic(nb, 'deadLetters'),
  fragment: () => ({
    nodes: [{ key: 'dlq', type: 'queue', queueKind: 'queue', deliveryRole: 'dead-letter' }],
    // Three attempts is the conventional default — the one opinion `addDeadLetterQueue` has too.
    edges: [{ from: 'anchor', to: 'dlq', deliveryAttempts: 3 }],
  }),
};

const STREAM_DEAD_LETTER: ContinuationRule = {
  id: 'stream-dead-letter',
  tier: 'secondary',
  label: 'Dead-letter topic',
  reason: 'This stream has a consumer but no dead-letter path.',
  // The literal `queueKind === 'stream'`, not `categoryOf` (which folds it into `queue`) — a
  // Stream's dead-letter destination reads as a Topic, unlike a plain Queue's. The fragment below
  // still resolves to the existing, already-valid `queue>deadLetter` matrix row regardless: giving
  // the new node `deliveryRole: 'dead-letter'` puts it in `NodeCategory: 'deadLetter'` no matter
  // what its `queueKind` is (see `categoryOf`'s precedence) — no new matrix row needed, `queueKind`
  // only changes how it's drawn.
  when: (nb) =>
    nb.node.type === 'queue' &&
    nb.node.queueKind === 'stream' &&
    hasOutboundSemantic(nb, 'consumes') &&
    !hasOutboundSemantic(nb, 'deadLetters'),
  fragment: () => ({
    nodes: [{ key: 'dlq', type: 'queue', queueKind: 'topic', deliveryRole: 'dead-letter' }],
    edges: [{ from: 'anchor', to: 'dlq', deliveryAttempts: 3 }],
  }),
};

const GATEWAY_ROUTE: ContinuationRule = {
  id: 'gateway-route',
  tier: 'primary',
  label: 'Service',
  reason: "This gateway doesn't route to anything yet.",
  when: (nb, trigger) => nb.category === 'gateway' && (trigger === 'drop' || (nb.in.length > 0 && nb.out.length === 0)),
  fragment: () => ({
    nodes: [{ key: 'service', type: 'service', serviceKind: 'api' }],
    edges: [{ from: 'anchor', to: 'service' }],
  }),
  repeatable: (trigger) => trigger === 'drop',
};

/**
 * A Scheduler with nothing to trigger yet — `MATRIX['scheduler>service']` and
 * `['scheduler>worker']` both default to `'triggers'`. Unlike the fan-out families above, no
 * inbound evidence is required: a Scheduler fires on its own interval, not because something fed
 * it, so "has it triggered anything downstream" is the whole question.
 */
const SCHEDULER_TRIGGER = defineFanOut(
  ['scheduler'],
  (nb) => nb.out.length === 0,
  [
    {
      id: 'scheduler-trigger-service',
      tier: 'primary',
      label: 'Service',
      reason: "This scheduler doesn't trigger anything yet.",
      node: { type: 'service' },
    },
    {
      id: 'scheduler-trigger-worker',
      tier: 'secondary',
      label: 'Worker',
      reason: 'A scheduled job is usually a Worker.',
      node: { type: 'service', serviceKind: 'worker' },
    },
  ],
);

/**
 * An Object Storage bucket already being written to with nowhere for that write to notify —
 * `MATRIX['objectStorage>queue']`/`['objectStorage>topic']` (both `publishes`/`event`), the one
 * storage kind that legitimately triggers a downstream event. Same "already receiving, nothing
 * leaves yet" evidence the Topic fan-out above uses, reused via `defineFanOut` rather than
 * repeated by hand. There is no Worker target here — Object Storage has no `worker` row in the
 * matrix, so `fragmentIsValid` would reject one anyway; it is simply never offered as a target.
 */
const OBJECT_STORAGE_FAN_OUT = defineFanOut(
  ['objectStorage'],
  (nb) => hasInboundEvidence(nb) && !hasOutboundSemantic(nb, ...DELIVERY_SEMANTICS),
  [
    {
      id: 'object-storage-fan-out-queue',
      tier: 'primary',
      label: 'Queue',
      reason: 'Uploads here have nowhere to notify yet.',
      node: { type: 'queue', queueKind: 'queue' },
    },
    {
      id: 'object-storage-fan-out-topic',
      tier: 'secondary',
      label: 'Topic',
      reason: 'Multiple subscribers can watch this bucket through a topic instead.',
      node: { type: 'queue', queueKind: 'topic' },
    },
  ],
);

/**
 * A Port already depended on but not implemented by anything — `MATRIX['port>component']`/
 * `['port>service']` (both `implementedBy`). Same "has inbound, nothing routed yet" evidence
 * `gateway-route` below already uses.
 */
const PORT_IMPLEMENTATION = defineFanOut(
  ['port'],
  (nb) => hasInboundEvidence(nb) && nb.out.length === 0,
  [
    {
      id: 'port-implementation-component',
      tier: 'primary',
      label: 'Component',
      reason: "This port isn't implemented by anything yet.",
      node: { type: 'component' },
    },
    {
      id: 'port-implementation-service',
      tier: 'secondary',
      label: 'Service',
      reason: 'A port can also be implemented by a whole service.',
      node: { type: 'service' },
    },
  ],
);

/**
 * A Worker already fed by something but with no outbound connection at all yet — narrower than
 * the other families' evidence (zero outbound of *any* kind, not just a missing delivery path),
 * since "should this worker index something" is otherwise exactly the kind of guess `docs/
 * SEMANTICS.md` warns a plain Service against. `MATRIX['worker>searchIndex']` defaults to
 * `'indexes'` (overriding the generic `service>searchIndex` default of `'searches'`), so a Worker
 * is the one service-family kind with a real, opinionated row here — a plain Service still gets no
 * rule at all.
 */
const WORKER_INDEXES = defineFanOut(
  ['worker'],
  (nb) => hasInboundEvidence(nb) && nb.out.length === 0,
  [
    {
      id: 'worker-indexes',
      tier: 'secondary',
      label: 'Search Index',
      reason: "This worker doesn't index anything yet.",
      node: { type: 'database', databaseKind: 'search-index' },
    },
  ],
);

export const RULES: readonly ContinuationRule[] = [
  TOPIC_FAN_OUT_QUEUE,
  TOPIC_FAN_OUT_WORKER,
  QUEUE_CONSUMER,
  QUEUE_DEAD_LETTER,
  STREAM_DEAD_LETTER,
  GATEWAY_ROUTE,
  ...SCHEDULER_TRIGGER,
  ...OBJECT_STORAGE_FAN_OUT,
  ...PORT_IMPLEMENTATION,
  ...WORKER_INDEXES,
];

