import { describe, expect, it } from 'vitest';
import { toPlantUml } from '../src/sequence/plantuml';
import type { SequenceModel } from '../src/sequence/types';

function model(overrides: Partial<SequenceModel> = {}): SequenceModel {
  return { title: '', participants: [], elements: [], ...overrides };
}

describe('toPlantUml', () => {
  it('emits a valid, minimal skeleton for an empty, untitled model', () => {
    expect(toPlantUml(model())).toBe('@startuml\n@enduml\n');
  });

  it('includes a sparing header comment when the model has a title', () => {
    const out = toPlantUml(model({ title: 'Payment Saga' }));
    expect(out).toContain("' Generated by Draft Canvas from \"Payment Saga\"\n");
  });

  it('declares each participant kind with its own PlantUML keyword and alias', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'Customer', label: 'Customer', category: 'actor', kind: 'actor', sourceNodeId: 'n1' },
        { id: 'P2', alias: 'OrderAPI', label: 'Order API', category: 'service', kind: 'participant', sourceNodeId: 'n2' },
        { id: 'P3', alias: 'OrdersDB', label: 'Orders DB', category: 'database', kind: 'database', sourceNodeId: 'n3' },
        { id: 'P4', alias: 'OrderEvents', label: 'Order Events', category: 'topic', kind: 'queue', sourceNodeId: 'n4' },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('actor "Customer" as Customer');
    expect(out).toContain('participant "Order API" as OrderAPI');
    expect(out).toContain('database "Orders DB" as OrdersDB');
    expect(out).toContain('queue "Order Events" as OrderEvents');
  });

  it('uses the sync/response/async arrow for each interaction kind, and the alias in every arrow', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Call', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
            { kind: 'message', order: 1, from: 'P2', to: 'P1', label: 'OK', interaction: 'response', isResponse: true, sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
            { kind: 'message', order: 2, from: 'P1', to: 'P2', label: 'Publish', interaction: 'async', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('A -> B: Call');
    expect(out).toContain('B --> A: OK');
    expect(out).toContain('A ->> B: Publish');
  });

  it('does not need to escape a literal colon in a message label', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'HTTP 200: OK', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    expect(toPlantUml(m)).toContain('A -> B: HTTP 200: OK');
  });

  it('never emits an empty message label', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: '  ', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    expect(toPlantUml(m)).toContain(': Message');
  });

  it('escapes a double quote in a participant name', () => {
    const m = model({
      participants: [{ id: 'P1', alias: 'Gateway', label: 'The "Gateway"', category: 'service', kind: 'participant', sourceNodeId: 'a' }],
    });
    expect(toPlantUml(m)).toContain('participant "The \\"Gateway\\"" as Gateway');
  });

  it("wraps a flow's messages in a native group <label> ... end block", () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Happy Path',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Go', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('group Happy Path\n');
    expect(out).toContain('    A -> B: Go');
    expect(out.match(/^end$/m)).toHaveLength(1);
  });

  it('emits two separate group blocks for two flows, never merging them', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Happy Path',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Go', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
        {
          kind: 'group',
          id: 'f2',
          label: 'Compensation',
          sourceFlowId: 'f2',
          children: [{ kind: 'message', order: 1, from: 'P2', to: 'P1', label: 'Undo', interaction: 'sync', sourceFlowId: 'f2', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('group Happy Path\n');
    expect(out).toContain('group Compensation\n');
    expect(out.match(/^end$/gm)).toHaveLength(2);
  });

  it('renders a note as a real multi-line block, with the portable prefix on the first content line', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'note', order: 0, participantIds: ['P1', 'P2'], text: 'Should this retry?', noteKind: 'question', sourceFlowId: 'f1' },
          ],
        },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('note over A,B\n');
    expect(out).toContain('Question: Should this retry?\n');
    expect(out).toContain('end note\n');
  });

  it('wraps a long note instead of letting one sentence stretch the diagram sideways', () => {
    const long =
      'Compensation is event-driven too: Payment refunds and publishes Payment Refunded; Order reacts to that in turn.';
    const m = model({
      participants: [{ id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' }],
      elements: [{ kind: 'note', order: 0, participantIds: ['P1'], text: long, sourceFlowId: 'f1' }],
    });
    const lines = toPlantUml(m).split('\n');
    const start = lines.findIndex((line) => line.trim().startsWith('note over'));
    const end = lines.findIndex((line) => line.trim() === 'end note');
    const body = lines.slice(start + 1, end);

    expect(body.length).toBeGreaterThan(1);
    for (const line of body) expect(line.trim().length).toBeLessThanOrEqual(60);
    expect(body.map((line) => line.trim()).join(' ')).toBe(long);
  });

  it('preserves multiple lines of Code verbatim, one line per source line, no collapsing', () => {
    const m = model({
      participants: [{ id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' }],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            {
              kind: 'note',
              order: 0,
              participantIds: ['P1'],
              text: 'if (a < b) {\n  retry();\n}',
              language: 'typescript',
              sourceFlowId: 'f1',
            },
          ],
        },
      ],
    });
    const out = toPlantUml(m);
    expect(out).toContain('if (a < b) {\n');
    expect(out).toContain('retry();\n');
    expect(out).toContain('}\n');
  });

  it('is deterministic — the same model always produces byte-identical output', () => {
    const m = model({
      title: 'Payment Saga',
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Go', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    expect(toPlantUml(m)).toBe(toPlantUml(m));
  });
});
