import { describe, expect, it } from 'vitest';
import { toMermaid } from '../src/sequence/mermaid';
import type { SequenceElement, SequenceModel } from '../src/sequence/types';

function model(overrides: Partial<SequenceModel> = {}): SequenceModel {
  return { title: '', participants: [], elements: [], ...overrides };
}

describe('toMermaid', () => {
  it('emits a valid, minimal skeleton for an empty, untitled model', () => {
    expect(toMermaid(model())).toBe('sequenceDiagram\n');
  });

  it('includes a sparing header comment when the model has a title', () => {
    const out = toMermaid(model({ title: 'Payment Saga' }));
    expect(out).toContain('%% Generated by Draft Canvas from "Payment Saga"\n');
  });

  it('declares each participant with the right keyword and an aliased, quoted name', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'Customer', label: 'Customer', category: 'actor', kind: 'actor', sourceNodeId: 'n1' },
        { id: 'P2', alias: 'OrderAPI', label: 'Order API', category: 'service', kind: 'participant', sourceNodeId: 'n2' },
        { id: 'P3', alias: 'OrdersDB', label: 'Orders DB', category: 'database', kind: 'database', sourceNodeId: 'n3' },
      ],
    });
    const out = toMermaid(m);
    expect(out).toContain('actor Customer as "Customer"');
    expect(out).toContain('participant OrderAPI as "Order API"');
    // Mermaid has no `database` keyword — falls back to plain participant.
    expect(out).toContain('participant OrdersDB as "Orders DB"');
  });

  it('uses the sync/response/async arrow for each interaction kind, and the alias in every arrow', () => {
    const elements: SequenceElement[] = [
      { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Call', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
      { kind: 'message', order: 1, from: 'P2', to: 'P1', label: 'OK', interaction: 'response', isResponse: true, sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
      { kind: 'message', order: 2, from: 'P1', to: 'P2', label: 'Publish', interaction: 'async', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
    ];
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [{ kind: 'group', id: 'f1', label: 'Flow', sourceFlowId: 'f1', children: elements }],
    });
    const out = toMermaid(m);
    expect(out).toContain('A->>B: Call');
    expect(out).toContain('B-->>A: OK');
    expect(out).toContain('A-)B: Publish');
  });

  it('writes `;` and `#` in a message label as entity codes, so neither ends the statement', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Retry #2; then give up', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    expect(toMermaid(m)).toContain('A->>B: Retry #35;2#59; then give up');
  });

  it('guards a literal colon in a message label', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'HTTP 200: OK', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    expect(toMermaid(m)).toContain('HTTP 200- OK');
  });

  it('never emits an empty message label', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: '  ', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    expect(toMermaid(m)).toContain(': Message');
  });

  it('escapes a double quote and disambiguated duplicate names cleanly', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'Service', label: 'Service', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'Service2', label: 'Service (2)', category: 'service', kind: 'participant', sourceNodeId: 'b' },
        { id: 'P3', alias: 'Gateway', label: 'The "Gateway"', category: 'service', kind: 'participant', sourceNodeId: 'c' },
      ],
    });
    const out = toMermaid(m);
    expect(out).toContain('participant Service as "Service"');
    expect(out).toContain('participant Service2 as "Service (2)"');
    expect(out).toContain('participant Gateway as "The \\"Gateway\\""');
  });

  it('escapes a backslash before a quote without letting it swallow the closing quote', () => {
    // Escaping `"` before `\` would turn a label ending `\"` into `\\"` — read as an escaped
    // backslash followed by a bare, string-closing quote, which breaks out of the declaration.
    const raw = 'C:\\Users\\"Bob"';
    const m = model({
      participants: [{ id: 'P1', alias: 'A', label: raw, category: 'service', kind: 'participant', sourceNodeId: 'a' }],
    });
    const line = toMermaid(m).split('\n').find((l) => l.includes('participant A as'))!;
    const match = line.match(/^\s*participant A as "(.*)"$/);
    expect(match).not.toBeNull();
    // Decode the same way a real parser would — unescape `\"` before `\\` — and recover the
    // original label. A wrong escape order corrupts this round-trip.
    const decoded = match![1]!.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    expect(decoded).toBe(raw);
  });

  it("wraps a flow's messages in a rect block with a synthesized title Note", () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'Customer', label: 'Customer', category: 'actor', kind: 'actor', sourceNodeId: 'a' },
        { id: 'P2', alias: 'OrderAPI', label: 'Order API', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Happy Path',
          sourceFlowId: 'f1',
          children: [
            { kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Place Order', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] },
          ],
        },
      ],
    });
    const out = toMermaid(m);
    expect(out).toContain('    rect rgb(240, 240, 240)\n');
    expect(out).toContain('Note over Customer,OrderAPI: Happy Path');
    expect(out).toContain('Customer->>OrderAPI: Place Order');
    expect(out.match(/end/g)).toHaveLength(1);
  });

  it('emits two separate rect blocks for two flows, never merging them', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Happy Path',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Go', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
        {
          kind: 'group',
          id: 'f2',
          label: 'Compensation',
          sourceFlowId: 'f2',
          children: [{ kind: 'message', order: 1, from: 'P2', to: 'P1', label: 'Undo', interaction: 'sync', sourceFlowId: 'f2', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    const out = toMermaid(m);
    expect(out.match(/rect rgb\(240, 240, 240\)/g)).toHaveLength(2);
    expect(out).toContain('Note over A,B: Happy Path');
    expect(out).toContain('Note over B,A: Compensation');
  });

  it('renders a Question with a portable "Question: " prefix, a plain Note with no prefix', () => {
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            { kind: 'note', order: 0, participantIds: ['P1', 'P2'], text: 'Idempotent', noteKind: 'note', sourceFlowId: 'f1' },
            { kind: 'note', order: 1, participantIds: ['P1', 'P2'], text: 'Should this retry?', noteKind: 'question', sourceFlowId: 'f1' },
            { kind: 'note', order: 2, participantIds: ['P1'], text: 'Rate limited', noteKind: 'warning', sourceFlowId: 'f1' },
            { kind: 'note', order: 3, participantIds: ['P1'], text: 'Chose retry', noteKind: 'decision', sourceFlowId: 'f1' },
          ],
        },
      ],
    });
    const out = toMermaid(m);
    expect(out).toContain('Note over A,B: Idempotent');
    expect(out).toContain('Note over A,B: Question: Should this retry?');
    expect(out).toContain('Note over A: Warning: Rate limited');
    expect(out).toContain('Note over A: Decision: Chose retry');
  });

  it('wraps a long note into <br/>-separated lines instead of one very wide box', () => {
    const long =
      'Compensation is event-driven too: Payment refunds and publishes Payment Refunded; Order reacts to that in turn.';
    const m = model({
      participants: [{ id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' }],
      elements: [{ kind: 'note', order: 0, participantIds: ['P1'], text: long, sourceFlowId: 'f1' }],
    });
    const note = toMermaid(m)
      .split('\n')
      .map((line) => line.trim())
      .find((line) => line.startsWith('Note over A:'))!;
    const segments = note.replace('Note over A: ', '').split('<br/>');

    expect(segments.length).toBeGreaterThan(1);
    for (const segment of segments) expect(segment.length).toBeLessThanOrEqual(60);
    // Colons are still guarded, so compare against the same substitution the emitter makes.
    expect(segments.join(' ')).toBe(long.replace(/:/g, '-').replace(/;/g, '#59;'));
  });

  it('collapses a multi-line note (e.g. Code) into one line via <br/>, escaping HTML-sensitive characters', () => {
    const m = model({
      participants: [{ id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' }],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [
            {
              kind: 'note',
              order: 0,
              participantIds: ['P1'],
              text: 'if (a < b && b > c) {\n  retry();\n}',
              language: 'typescript',
              sourceFlowId: 'f1',
            },
          ],
        },
      ],
    });
    const out = toMermaid(m);
    // Mermaid entity codes, not HTML entities: `&lt;`'s own `;` (and the code's `;`) would end the
    // statement mid-note.
    expect(out).toContain('Note over A: if (a #lt; b #amp;#amp; b #gt; c) {<br/>retry()#59;<br/>}');
  });

  it('does not truncate a very long message label', () => {
    const longLabel = 'Process the order and reserve inventory across every regional warehouse'.repeat(3);
    const m = model({
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: longLabel, interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    expect(toMermaid(m)).toContain(longLabel);
  });

  it('is deterministic — the same model always produces byte-identical output', () => {
    const m = model({
      title: 'Payment Saga',
      participants: [
        { id: 'P1', alias: 'A', label: 'A', category: 'service', kind: 'participant', sourceNodeId: 'a' },
        { id: 'P2', alias: 'B', label: 'B', category: 'service', kind: 'participant', sourceNodeId: 'b' },
      ],
      elements: [
        {
          kind: 'group',
          id: 'f1',
          label: 'Flow',
          sourceFlowId: 'f1',
          children: [{ kind: 'message', order: 0, from: 'P1', to: 'P2', label: 'Go', interaction: 'sync', sourceFlowId: 'f1', sourceEdgeIds: [], sourceStepIds: [] }],
        },
      ],
    });
    expect(toMermaid(m)).toBe(toMermaid(m));
  });
});
