import { memo, useMemo } from 'react';
import { useEditorStore } from '../store/editorStore';
import { resolveEdgeColor } from '../edges/kindStyle';
import { markerDefs } from '../render/svg/markers';
import { shadowFilter } from '../render/svg/emit';
import { serialize } from '../render/svg/element';
import { PERSONALITY_PROFILES } from '../render/roughness/presets';
import { usePersonality } from '../ui/personality/usePersonality';
import { useThemeValue } from '../ui/theme/useTheme';

/**
 * Arrowheads and the one drop shadow, mounted once for the whole canvas.
 *
 * They are generated by the same functions the exporter uses, so an arrow on
 * screen and an arrow in an exported file are the same geometry rather than two
 * similar ones.
 *
 * Memoized on its actual inputs, and the component itself wrapped in `memo`
 * (it takes no props, so that's a pure "skip unless a subscribed value
 * actually changed" gate): `Canvas` re-renders on essentially every editor
 * state change, selection included, and without this a `dangerouslySetInnerHTML`
 * this large gets its `<defs>` torn down and rebuilt — every `<marker>` arrowhead
 * removed and reinserted — on each of those, even though the markup is
 * byte-identical every time. Safari has been seen to flicker a directed edge's
 * arrowhead specifically during that churn, since it has to re-resolve the
 * edge's `marker-end` `url(#...)` reference against a marker element that was
 * just removed and recreated; an edge with no arrowhead has nothing depending
 * on `<defs>` staying put, which is why the flicker tracks "has an arrow," not
 * "is selected."
 */
export const Markers = memo(function Markers() {
  const theme = useThemeValue();
  const { preset } = usePersonality();
  const edges = useEditorStore((state) => state.document.edges);
  const nodes = useEditorStore((state) => state.document.nodes);

  const markup = useMemo(() => {
    const nodesById = new Map(nodes.map((node) => [node.id, node]));
    const colors = new Set<string>([theme.edge, theme.selection]);
    for (const edge of edges) {
      colors.add(resolveEdgeColor(edge, nodesById.get(edge.source), theme));
    }
    return [shadowFilter(theme.shadow), ...markerDefs(colors, PERSONALITY_PROFILES[preset].arrowJitter)]
      .map(serialize)
      .join('');
  }, [nodes, edges, theme, preset]);

  return (
    <svg
      className="dc-defs"
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: `<defs>${markup}</defs>` }}
    />
  );
});
