import { useEditorStore } from '../store/editorStore';
import { accentOf } from '../render/theme/tokens';
import { markerDefs } from '../render/svg/markers';
import { shadowFilter } from '../render/svg/emit';
import { serialize } from '../render/svg/element';
import { useThemeValue } from '../ui/theme/useTheme';

/**
 * Arrowheads and the one drop shadow, mounted once for the whole canvas.
 *
 * They are generated by the same functions the exporter uses, so an arrow on
 * screen and an arrow in an exported file are the same geometry rather than two
 * similar ones.
 */
export function Markers() {
  const theme = useThemeValue();
  const edges = useEditorStore((state) => state.document.edges);

  const colors = new Set<string>([theme.edge]);
  for (const edge of edges) {
    const palette = accentOf(theme, edge.accent);
    colors.add(edge.accent && edge.accent !== 'neutral' ? palette.chip : theme.edge);
  }
  colors.add(theme.selection);

  const markup = [shadowFilter(theme.shadow), ...markerDefs(colors)].map(serialize).join('');

  return (
    <svg
      className="dc-defs"
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: `<defs>${markup}</defs>` }}
    />
  );
}
